ProductionPractice/DjangoMySite/mysite/urls.py
from django.conf.urls import url, patterns, include
from django.contrib import admin

from online import views as online

urlpatterns = [
    url(r'^$', online.login, name = 'login'),
    url(r'^admin/', admin.site.urls),
    url(r'^online/', include('online.urls')),
]

ProductionPractice/DjangoMySite/online/urls.py
from django.conf.urls import url

from . import views

app_name = 'online'
urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^login/$',views.login,name = 'login'),
    url(r'^regist/$',views.regist,name = 'regist'),
    url(r'^commodity/$', views.commodity, name = 'commodity'),
    url(r'^add_commodity/$', views.add_commodity, name = 'add_commodity'),
    url(r'^logout/$',views.logout,name = 'logout'),
    url(r'^get_user_info/$', views.get_user_info, name = 'get_user_info'),
    url(r'^captcha/$', views.captcha, name = 'captcha'),
]

ProductionPractice/DjangoMySite/online/models.py
from __future__ import unicode_literals

from django.db import models


class Adminuser(models.Model):
    username = models.CharField(primary_key=True, max_length=5)
    password = models.CharField(max_length=32)

    class Meta:
        managed = False
        db_table = 'AdminUser'

    def __str__(self):
        return username


class Commodity(models.Model):
    id = models.CharField(primary_key=True, max_length=8)
    name = models.CharField(max_length=1024)
    price = models.IntegerField()
    store = models.IntegerField()
    info = models.CharField(max_length=10240, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Commodity'


class Image(models.Model):
    commodity = models.ForeignKey(Commodity, on_delete=models.CASCADE)
    img_path = models.CharField(max_length=1024)

    class Meta:
        managed = False
        db_table = 'Image'


class Orders(models.Model):
    order_id = models.AutoField(primary_key=True)
    order_date = models.DateTimeField()
    total = models.IntegerField()
    status = models.IntegerField()
    username = models.ForeignKey('User', on_delete=models.CASCADE, db_column='username')

    class Meta:
        managed = False
        db_table = 'Orders'


class Ordersinfo(models.Model):
    order = models.ForeignKey(Orders, on_delete=models.CASCADE)
    commodity = models.ForeignKey(Commodity, on_delete=models.CASCADE)
    counter = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'OrdersInfo'
        unique_together = (('order', 'commodity'),)


class Shoppingcart(models.Model):
    username = models.ForeignKey('User', on_delete=models.CASCADE, db_column='username')
    commodity = models.ForeignKey(Commodity, on_delete=models.CASCADE)
    counter = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'ShoppingCart'
        unique_together = (('username', 'commodity'),)


class User(models.Model):
    username = models.CharField(primary_key=True, max_length=255)
    password = models.CharField(max_length=32)
    phone = models.CharField(max_length=11)
    email = models.CharField(max_length=32)
    addr = models.CharField(max_length=1024)

    class Meta:
        managed = False
        db_table = 'User'

    def __str__(self):
        return username

ProductionPractice/DjangoMySite/online/views.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render,render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader, RequestContext
from online.models import User, Adminuser, Commodity
from django.views import generic
from django.contrib import messages

import random
import json
import hashlib
from PIL import Image, ImageDraw, ImageFont

def commodity(request):
    if request.method == 'GET':
        return render(request, 'online/commodity.html')

@csrf_exempt
def regist(request):
    if request.method == 'GET':
        return render(request, 'online/regist.html')
    elif request.method == 'POST':
        captcha = request.POST.get('captcha')
        if captcha != request.session.get('captcha', None):
            return JsonResponse({'code': 1, 'msg': 'invalid captcha'})

        try:
            username = request.POST.get('username')
            password = request.POST.get('password')
            phone = request.POST.get('phone')
            email = request.POST.get('email')
            addr = request.POST.get('addr')

            md5 = hashlib.md5()
            md5.update(password.encode())
            password_md5 = md5.hexdigest()

            User.objects.create(
                username = username,
                password = password_md5,
                phone = phone,
                email = email,
                addr = addr
            )
        except Exception as e:
            return JsonResponse({
                'code': 2,
                'msg': 'Create User failed, error: ' + str(e)
            })
        return JsonResponse({'code': 0, 'msg': 'success'})


# Login
def login(request):
    if request.method == 'GET':
        return render(request, 'online/login.html')

    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        md5 = hashlib.md5()
        md5.update(password.encode())
        passwd_md5 = md5.hexdigest()

        user = Adminuser.objects.filter(username = username, password = passwd_md5)
        if user:
            response = HttpResponseRedirect('/online/add_commodity/')
            response.set_cookie('username', username, 3600)
            return HttpResponseRedirect('/online/add_commodity/')
        else:
            return HttpResponseRedirect('/online/')

@csrf_exempt
def add_commodity(request):
    if request.method == 'GET':
        return render(request, 'online/add_commodity.html')
    elif request.method == 'POST':
        try:
                id = request.POST.get('id')
                name = request.POST.get('name')
                price = request.POST.get('price')
                store = request.POST.get('store')
                info = request.POST.get('messageArea')

                Commodity.objects.create(
                    id = id,
                    name  = name,
                    price  = price,
                    store = store,
                    info = info
                )
        except Exception as e:
            return JsonResponse({
                'code': 2,
                'msg': 'Create Commodity failed, error: ' + str(e)
            })
        return JsonResponse({'code': 0, 'msg': 'success'})

def logout(req):
    response = HttpResponseRedirect('/online/')
    response.delete_cookie('username')
    return response

def get_user_info(req):
    if req.method == 'GET':
        username = req.COOKIES.get('username','')
        user = User.objects.get(username = username)
        userdict = {
            'username':username,
            'email': user.email,
            'birthday': user.birthday,
            'birthplace': user.birthplace,
            'gender': user.gender,
            'hobby': user.hobby,
            'info': user.info
        }
        return JsonResponse(userdict)

def gen_captcha(text, response):
    image_width = len(text) * 14
    image_height = 27
    color = (0,0,0,255)
    font = ImageFont.truetype('Ubuntu-B.ttf', 24)

    txt = Image.new('RGB', (image_width, image_height), (255,255,255))
    d = ImageDraw.Draw(txt)
    d.text((0,0), text, font=font, fill=color)
    txt.save(response, "jpeg")

def captcha(req):
    if req.method == 'GET':
        response = HttpResponse(content_type='image/jpeg')
        captcha_str = str(random.randrange(1000, 9999))
        gen_captcha(captcha_str, response)
        req.session['captcha'] = captcha_str
        return response

ProductionPractice/DjangoMySite/online/templates/online/add_commodity.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">

  <head>
    <meta charset="utf-8">
    <meta name="author" content="Joyce Lee">

    <link rel="stylesheet" type="text/css" href={% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}>

    <script type="text/javascript" src={% static 'node_modules/jquery/dist/jquery.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/jqueryui/jquery-ui.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/ckeditor/ckeditor.js' %}></script>
    <script type="text/javascript" src={% static 'online/js/js-add_commodity.js' %}></script>

    <title>Add Commodity</title>
  </head>

  <body>
    {% include "online/nav-header.partial.html" %}
    <div style="width: 100%; background-color: #FFFFCC; text-align: center;">
      <h3>Welcome! Add Commodity here.</h3>
    </div>

    <div class="col-sm-5" style="width: 80%; margin: 1% 10%;">
      <div class="panel panel-default">
        <div class="panel-body">
          <form id="add_commodity_form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">ID</span>
              <input name="commodity_id" type="text" class="form-control"
                      placeholder="Please enter 8 Char for commodity ID..."
                      aria-describedby="basic-addon1">
              <span id="tips"></span>
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Name</span>
              <input name="commodity_name" type="text" class="form-control"
                      placeholder="Please enter commodity name..."
                      aria-describedby="basic-addon1">
              <span id="tips"></span>
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Price</span>
              <input name="commodity_price" type="text" class="form-control"
                      placeholder="Please enter commodity price..."
                      aria-describedby="basic-addon1">
              <span id="tips"></span>
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Store</span>
              <input name="commodity_store" type="text" class="form-control"
                      placeholder="Please enter commodity store..."
                      aria-describedby="basic-addon1">
              <span id="tips"></span>
            </div>
            <br />

            <div>
              <span class="input-group-addon" id="basic-addon1">Info</span>
              <textarea id="editor" name="messageArea"></textarea>
              <div class="fileinput fileinput-new" data-provides="fileinput" style="width: 100%"></div>
            <br />

            <div>
              <input type="button" value="submit" class="btn btn-default btn-block" style="width: 50%; float: right;" onclick="submit_onclick_commodity(event)" />
              <input type="reset" value="Reset" class="btn btn-default btn-block" style="width: 50%;" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

ProductionPractice/DjangoMySite/online/templates/online/commodity.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">

  <head>
    <meta charset="utf-8">
    <meta name="author" content="Joyce Lee">

    <link rel="stylesheet" type="text/css" href={% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}>

    <title>Commodity</title>
  </head>

  <body>
    {% include "online/nav-header.partial.html" %}
    <div style="width: 100%; height: 300px; background-color: #FFFFCC;">
      <h1>Hello, Welcome</h1>
    </div>

  </body>
</html>

ProductionPractice/DjangoMySite/online/templates/online/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">

  <head>
    <meta charset="utf-8">
    <meta name="author" content="Joyce Lee">

    <link rel="stylesheet" type="text/css" href={% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'node_modules/jasny-bootstrap/dist/css/jasny-bootstrap.min.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'node_modules/jqueryui/jquery-ui.min.css'%}>
    <link rel="stylesheet" type="text/css" href={% static 'node_modules/jqueryui/jquery-ui.theme.min.css'%}>

    <script type="text/javascript" src={% static 'node_modules/jquery/dist/jquery.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/jasny-bootstrap/dist/js/jasny-bootstrap.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/jqueryui/jquery-ui.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/ckeditor/ckeditor.js' %}></script>
    <script type="text/javascript" src={% static 'online/js/js-form_vaildation.js' %}></script>
    <script type="text/javascript" src={% static 'online/js/js-index.js' %}></script>

    <title>Welcome</title>
  </head>

  <body>
    {% include "online/nav-header.partial.html" %}

    <div class="col-sm-5" style="width: 40%; margin: 1% 30%;">
      <div class="panel panel-default">
        <div class="panel-body">
          <form id="add_commodity_form" method = 'post' enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">ID</span>
              <input name="commodity_id" type="text" class="form-control"
                      placeholder="Please enter 8 Char for commodity ID..."
                      aria-describedby="basic-addon1">
              <span id="tips"></span>
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Name</span>
              <input name="commodity_id" type="text" class="form-control"
                      placeholder="Please enter commodity name..."
                      aria-describedby="basic-addon1">
              <span id="tips"></span>
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Price</span>
              <input name="commodity_id" type="text" class="form-control"
                      placeholder="Please enter commodity price..."
                      aria-describedby="basic-addon1">
              <span id="tips"></span>
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Email</span>
              <input name="email" type="text" class="form-control"
                      placeholder="Please enter your email..."
                      aria-describedby="basic-addon1">
            </div>
            <br />

            <div>
              <span class="input-group-addon" id="basic-addon1">Info</span>
              <textarea id="editor" name="messageArea">Enter your info...</textarea>
              <div class="fileinput fileinput-new" data-provides="fileinput" style="width: 100%">
                <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 100%; height: 150px;"></div>
                <div>
                  <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><input type="file" name="..."></span>
                  <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                </div>
              </div>
            </rdiv>
            <br />
            
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon2">Captcha</span>
              <input type="text" name="captcha" class="form-control"
                      aria-describedby="basic-addon1" style="width: 50%;">
              <img src="/online/captcha/" alt="Captcha">
            </div>

            <div>
              <input type="button" value="submit" class="btn btn-default btn-block" style="width: 50%; float: right;" onclick="submit_onclick(event)" />
              <input type="reset" value="Reset" class="btn btn-default btn-block" style="width: 50%;" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

ProductionPractice/DjangoMySite/online/templates/online/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">

  <head>
    <meta charset="utf-8">
    <meta name="author" content="Joyce Lee">

    <link rel="stylesheet" type="text/css" href={% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}>
    <title>Login</title>
  </head>

  <body>
    {% include "online/nav-header.partial.html" %}

    <div class="col-sm-5" style="width: 40%; margin: 1% 30%;">
      <div class="panel panel-default">
        <div class="panel-body">
          <form method = 'post' enctype="multipart/form-data" onsubmit="return validate_form(this)">
            {% csrf_token %}
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">UserName</span>
              <input name="username" type="text" class="form-control"
                     aria-describedby="basic-addon1">
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon2">Password</span>
              <input name="password" type="password" class="form-control"
                     aria-describedby="basic-addon2">
            </div>
            <div>
              <input type="submit" value="submit" class="btn btn-default btn-block" style="width: 50%; float: right;" />
              <input type="reset" value="Reset" class="btn btn-default btn-block" style="width: 50%;" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

ProductionPractice/DjangoMySite/online/templates/online/logout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">

  <head>
    <meta charset="utf-8">
    <meta name="author" content="Joyce Lee">

    <link rel="stylesheet" type="text/css" href={% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'node_modules/jasny-bootstrap/dist/css/jasny-bootstrap.min.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'node_modules/jqueryui/jquery-ui.min.css'%}>
    <link rel="stylesheet" type="text/css" href={% static 'node_modules/jqueryui/jquery-ui.theme.min.css'%}>

    <script type="text/javascript" src={% static 'node_modules/jquery/dist/jquery.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/jasny-bootstrap/dist/js/jasny-bootstrap.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/jqueryui/jquery-ui.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/ckeditor/ckeditor.js' %}></script>
    <script type="text/javascript" src={% static 'online/js/js-form_vaildation.js' %}></script>
    <script type="text/javascript" src={% static 'online/js/js-regist.js' %}></script>

    <title>Regist</title>
  </head>

  <body>
    {% include "online/nav-header.partial.html" %}
    <div style="width: 100%; height: 300px; background-color: #FFFFCC;">
      <h1>Alread Logout</h1>
    </div>

  </body>
</html>

ProductionPractice/DjangoMySite/online/templates/online/nav-header.partial.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
         <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'online:commodity' %}">Shopping System</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="http://localhost:8080/shopping/html/products.jsp">Commodity<span class="sr-only"></span></a></li>
        <li class="active"><a href="{% url 'online:regist' %}">Regist<span class="sr-only"></span></a></li>
        <li class="active"><a href="{% url 'online:add_commodity' %}">Add Commodity<span class="sr-only">(current)</span></a></li>
        <li class="active"><a href="http://localhost:8080/html/index.jsp#login">Login<span class="sr-only"></span></a></li>
        <li class="active"><a href="{% url 'online:login' %}">Admin Login<span class="sr-only"></span></a></li>
        <li class="active"><a href="{% url 'online:logout' %}">Admin Logout<span class="sr-only"></span></a></li>
      </ul>
    </div>
  </div>
</nav>

ProductionPractice/DjangoMySite/online/templates/online/regist.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">

  <head>
    <meta charset="utf-8">
    <meta name="author" content="Joyce Lee">

    <link rel="stylesheet" type="text/css" href={% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}>
    <script type="text/javascript" src={% static 'node_modules/jquery/dist/jquery.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}></script>
    <script type="text/javascript" src={% static 'online/js/js-form_vaildation.js' %}></script>
    <script type="text/javascript" src={% static 'online/js/js-regist.js' %}></script>

    <title>Regist</title>
  </head>

  <body>
    {% include "online/nav-header.partial.html" %}
    <div class="col-sm-5" style="width: 40%; margin: 1% 30%;">
      <div class="panel panel-default">
        <div class="panel-body">
          <form id="register_form" method = 'post' enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">UserName</span>
              <input name="username" type="text" class="form-control"
                      placeholder="Please enter your username..."
                      aria-describedby="basic-addon1">
              <span id="tips"></span>
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon2">Password</span>
              <input name="password" type="password" class="form-control"
                      placeholder="Please enter your password..."
                      aria-describedby="basic-addon2">
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon2">Confirm</span>
              <input name="confirm_password" type="password" class="form-control"
                      placeholder="Please confirm your password..."
                      aria-describedby="basic-addon2">
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Phone</span>
              <input name="phone" type="text" class="form-control"
                      placeholder="Please enter your mobel phone number..."
                      aria-describedby="basic-addon1">
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Email</span>
              <input name="email" type="text" class="form-control"
                      placeholder="Please enter your email..."
                      aria-describedby="basic-addon1">
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Shopping Address</span>
              <input name="addr" type="text" class="form-control"
                      placeholder="Please enter your shopping address..."
                      aria-describedby="basic-addon1">
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon2">Captcha</span>
              <input type="text" name="captcha" class="form-control"
                      aria-describedby="basic-addon1" style="width: 50%;">
              <img src="/online/captcha/" alt="captcha">
            </div>

            <div>
              <input type="button" value="submit" class="btn btn-default btn-block" style="width: 50%; float: right;" onclick="submit_onclick(event)" />
              <input type="reset" value="Reset" class="btn btn-default btn-block" style="width: 50%;" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>