PythonInnovationPractice/version1/mysite/form/urls.py
from django.conf.urls import url

from . import views

app_name = 'form'

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^login/$', views.login, name='login'),
    url(r'^index/$',views.index, name='index'),
    url(r'^info/$', views.info, name='info'),
    url(r'^filling/$', views.filling, name='filling'),
    # url(r'^regist/$',views.regist,name = 'regist'),

    # # url(r'^logout/$',views.logout,name = 'logout'),
    # url(r'^get_user_info/$', views.get_user_info, name = 'get_user_info'),
    # url(r'^captcha/$', views.captcha, name = 'captcha'),
    # url(r'^update_info/$', views.update_info, name = 'update_info'),
]

PythonInnovationPractice/version1/mysite/form/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class Info(models.Model):
    autokey = models.AutoField(primary_key=True)
    id = models.CharField(max_length=255)
    password = models.ForeignKey('Uploadcode', models.DO_NOTHING, db_column='password')
    name = models.CharField(max_length=255)
    cellphone = models.CharField(max_length=11)
    email = models.CharField(max_length=255)
    gender = models.CharField(max_length=8, blank=True, null=True)
    birthday = models.CharField(max_length=255)
    birthplace = models.CharField(max_length=255)
    info = models.CharField(max_length=1024, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Info'


class Uploadcode(models.Model):
    uploadcode = models.CharField(primary_key=True, max_length=32)

    class Meta:
        managed = False
        db_table = 'Uploadcode'

PythonInnovationPractice/version1/mysite/form/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

import hashlib

# Login
def login(request):
    if request.method == 'GET':
        return render(request, 'form/login.html')

    elif request.method == 'POST':
        username = request.POST.get('username')
        passwd = request.POST.get('password')

        md5 = hashlib.md5()
        md5.update(passwd.encode())
        passwd_md5 = md5.hexdigest()

        user = User.objects.filter(username = username, passwd = passwd_md5)
        if user:
            response = HttpResponseRedirect('/form/index')
            response.set_cookie('username', username, 3600)
            return response
        else:
            return HttpResponseRedirect('/form/regist/')

def index(request):
    if request.method == 'GET':
        return HttpResponse("Hello, world. You're at the form index.")
    elif request.method == 'POST':
        pass

def info(request):
    if request.method == 'GET':
        return HttpResponse('Information.')

def filling(request):
    if request.method == 'GET':
        return HttpResponse('Filling.')

PythonInnovationPractice/version1/mysite/form/templates/form/index.html
<!DOCTYPE html>
<html lang="zh-cn">

  <head>
    <meta charset="utf-8">
    <meta name="author" content="Joyce Lee">

    <link rel="stylesheet" type="text/css" href={% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'node_modules/jasny-bootstrap/dist/css/jasny-bootstrap.min.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'node_modules/jqueryui/jquery-ui.min.css'%}>
    <link rel="stylesheet" type="text/css" href={% static 'node_modules/jqueryui/jquery-ui.theme.min.css'%}>

    <script type="text/javascript" src={% static 'node_modules/jquery/dist/jquery.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/jasny-bootstrap/dist/js/jasny-bootstrap.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/jqueryui/jquery-ui.min.js' %}></script>
    <script type="text/javascript" src={% static 'node_modules/ckeditor/ckeditor.js' %}></script>
    <script type="text/javascript" src={% static 'form/js/js-form_vaildation.js' %}></script>
    <script type="text/javascript" src={% static 'form/js/js-index.js' %}></script>

    <title>Welcome</title>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
             <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'form:login' %}">Form</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'form:login' %}">login<span class="sr-only">(current)</span></a></li>
            <li class="active"><a href="{% url 'form:filling' %}">Filling<span class="sr-only">(current)</span></a></li>
            <li class="active"><a href="{% url 'form:info' %}">Info<span class="sr-only">(current)</span></a></li>
            <li class="navbar-brand">Welcome {{username}}</li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="col-sm-5" style="width: 40%; margin: 1% 30%;">
      <div class="panel panel-default">
        <div class="panel-body">
          <form id="register_form" method = 'post' enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">UserName</span>
              <input name="username" type="text" class="form-control"
                      placeholder="Please enter your username..."
                      aria-describedby="basic-addon1">
              <span id="tips"></span>
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon2">Password</span>
              <input name="password" type="password" class="form-control"
                      placeholder="Please enter your password..."
                      aria-describedby="basic-addon2">
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon2">Confirm</span>
              <input name="confirm_password" type="password" class="form-control"
                      placeholder="Please confirm your password..."
                      aria-describedby="basic-addon2">
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Email</span>
              <input name="email" type="text" class="form-control"
                      placeholder="Please enter your email..."
                      aria-describedby="basic-addon1">
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Birthday</span>
              <input name="birthday" id="datepicker" type="text" class="form-control"
                      aria-describedby="basic-addon1" readonly="readonly"/>
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Birthplace</span>
              <select name="country" id="country">
              </select>
              <select name="city" id="city">
              </select>
            </div>
            <br />

            <div>
              <span class="input-group-addon" id="basic-addon1">Gender:</span>
              <input type="radio" name="gender" value="Male" checked="checked">Male
              <input type="radio" name="gender" value="Female">Female
            </div>
            <br />

            <div>
              <span class="input-group-addon" id="basic-addon1">Hobby:</span>
              <input type="checkbox" name="hobby" value="book" checked="checked">Books
              <input type="checkbox" name="hobby" value="music">Music
              <input type="checkbox" name="hobby" value="photo">Photo
              <input type="checkbox" name="hobby" value="sport">Sport
            </div>
            <br />

            <div>
              <span class="input-group-addon" id="basic-addon1">Info</span>
              <textarea id="editor" name="messageArea">Enter your info...</textarea>
              <div class="fileinput fileinput-new" data-provides="fileinput" style="width: 100%">
                <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 100%; height: 150px;"></div>
                <div>
                  <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><input type="file" name="..."></span>
                  <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                </div>
              </div>
            </rdiv>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon2">Captcha</span>
              <input type="text" name="captcha" class="form-control"
                      aria-describedby="basic-addon1" style="width: 50%;">
              <img src="/form/captcha/" alt="Captcha">
            </div>

            <div>
              <input type="button" value="submit" class="btn btn-default btn-block" style="width: 50%; float: right;" onclick="submit_onclick(event)" />
              <input type="reset" value="Reset" class="btn btn-default btn-block" style="width: 50%;" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

PythonInnovationPractice/version1/mysite/form/templates/form/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">

  <head>
    <meta charset="utf-8">
    <meta name="author" content="Joyce Lee">

    <link rel="stylesheet" type="text/css" href={% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}>
    <title>Login</title>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'form:login' %}">Form</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'form:login' %}">Login<span class="sr-only">(current)</span></a></li>
            <li class="active"><a href="{% url 'form:filling' %}">Filling<span class="sr-only">(current)</span></a></li>
            <li class="active"><a href="{% url 'form:info' %}">Info<span class="sr-only">(current)</span></a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="col-sm-5" style="width: 40%; margin: 1% 30%;">
      <div class="panel panel-default">
        <div class="panel-body">
          <form method = 'post' enctype="multipart/form-data" onsubmit="return validate_form(this)">
            {% csrf_token %}
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">UserName</span>
              <input name="username" type="text" class="form-control"
                     aria-describedby="basic-addon1">
            </div>
            <br />

            <div class="input-group">
              <span class="input-group-addon" id="basic-addon2">Password</span>
              <input name="password" type="password" class="form-control"
                     aria-describedby="basic-addon2">
            </div>
            <div>
              <input type="submit" value="submit" class="btn btn-default btn-block" style="width: 50%; float: right;" />
              <input type="reset" value="Reset" class="btn btn-default btn-block" style="width: 50%;" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>