PythonInnovationPractice/mysite/forms/urls.py
from django.conf.urls import url

from . import views

app_name = 'forms'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(),  name='index'),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/fill/$', views.fill, name='fill'),
]

PythonInnovationPractice/mysite/forms/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.utils.encoding import python_2_unicode_compatible
import datetime
from django.utils import timezone

@python_2_unicode_compatible
class Form(models.Model):
    form_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.form_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently'

@python_2_unicode_compatible
class Field(models.Model):
    form  = models.ForeignKey(Form, on_delete=models.CASCADE)
    field_text = models.CharField(max_length=200)
    answer = models.CharField(max_length=200)
    def __str__(self):
        return self.field_text

PythonInnovationPractice/mysite/forms/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import loader
from .models import Form, Field
from django.views import generic

from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt

import sqlite3

def save2db(ss):
    try:
        db = sqlite3.connect("./db.sqlite3")
        cursor = db.cursor()
        cursor.execute(ss)
        results = cursor.fetchall()
        for row in results:
            print(row)
        db.commit()
    except:
        db.rollback()
        print("database: something error.")
    finally:
        db.close()

class IndexView(generic.ListView):
    template_name = 'forms/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Form.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Form
    template_name = 'forms/detail.html'
    def get_queryset(self):
        return Form.objects.filter(pub_date__lte=timezone.now())

class ResultView(generic.DetailView):
    model = Form
    template_name = 'forms/results.html'

@csrf_exempt
def fill(request, question_id):
    form = get_object_or_404(Form, pk=question_id) # value: Test
    try:
        fields = form.field_set.all()
        print(fields)
        for i, field in enumerate(fields) :
            if i < 4:
                key = '{}'.format(field)
                value = request.POST.get(key)
                if value == '':
                    return render(request, 'forms/detail.html', {
                        'form': form,
                        'error_message': "Didn't fill in."
                    })
                else:
                    print(key, ':', value)
                    ss = """
                    INSERT INTO forms_field(field_text, answer, form_id) VALUES
                    ('{0}', '{1}', {2});
                    """.format(key, value, question_id)
                    save2db(ss)
    except (KeyError, Field.DoesNotExist):
        print('Some Error')
        return render(request, 'forms/detail.html', {
            'form': form,
            'error_message': "Didn't fill in."
        })
    else:
        print('hi, this is else.')
        return HttpResponseRedirect(reverse('forms:results', args=(form.id,)))

PythonInnovationPractice/mysite/forms/templates/forms/detail.html
<!--{% load staticfiles %}
<script type="text/javascript" src={% static 'forms/js/js-detail.js' %}></script>
-->
<h1>{{ form.form_text }}</h1>

{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}

<form method="post" action="{% url 'forms:fill' form.id %}">
{% csrf_token %}
{% for field in form.field_set.all %}
{% if forloop.counter <= 4 %}
    <label for="{{ field.field_text }}">{{ field.field_text }}</label>
    <input type="text"
           name="{{ field.field_text }}"
           value="" />
<br />
{% endif %}
{% endfor %}
<input type="submit" value="Submit" />
</form>

PythonInnovationPractice/mysite/forms/templates/forms/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li>
              <a href="{% url 'forms:detail' question.id %}">{{ question.form_text }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No forms are available.</p>
{% endif %}

PythonInnovationPractice/mysite/forms/templates/forms/results.html
<h1>{{ form.form_text }}</h1>

<ul>
{% for field in form.field_set.all %}
    <li>
        {{ field.field_text  }} -- {{ field.answer }}
    </li>
{% endfor %}
</ul>